config/routes.rb
Rails.application.routes.draw do
  root to: "pages#show", page: "solutions-journalism"
  resources :posts do
    resources :comments
  end
  get "/pages/:page" => "pages#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord



  after_create_commit {broadcast_prepend_to "posts"}
  after_update_commit {broadcast_replace_to "posts"}
  after_destroy_commit {broadcast_remove_to "posts"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def coderay(text)
    text.gsub(/\<code( lang="(.+?)")?\>(.+?)\<\/code\>/m) do
      CodeRay.scan($3, $2).div(:css => :class)
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@post, partial: "posts/form", locals: { post: @post}) }
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :publish_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # require 'redcarpet'
  # require 'rouge'
  # require 'rouge/plugins/redcarpet'
  #
  # class HTML < Redcarpet::Render::HTML
  #   include Rouge::Plugins::Redcarpet
  #
  #   def block_code(code, language)
  #     Rouge.highlight(code, language || 'text', 'html')
  #   end
  # end




end

app/helpers/rouge_helper.rb
module RougeHelper
  require 'redcarpet'
  require 'rouge'
  require 'rouge/plugins/redcarpet'

  class HTML < Redcarpet::Render::HTML
    include Rouge::Plugins::Redcarpet
  end

  def rouge_markdown(text)
    render_options = {
        filter_html: true,
        hard_wrap: true,
        link_attributes: { rel: 'nofollow' }
    }
    renderer = HTML.new(render_options)

    extensions = {
        autolink: true,
        fenced_code_blocks: true,
        lax_spacing: true,
        no_intra_emphasis: true,
        strikethrough: true,
        superscript: true
    }
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solutions Journalism - Lead Rails Developer - Travis Glover</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, id: dom_id(post), class: "needs-validation", data: {controller: "form"}) do |form| %>
    <h5 class="mb-3">New Post</h5>
    <div class="row g-3">
      <div class="field col-sm-6">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, required: true, class: "form-control form-control-md" %>
      </div>
      <div class="field col-sm-6">
        <%= form.label :publish_date %>
        <%= form.date_select :publish_date, class: "form-control form-control-md" %>
      </div>
      <hr class="my-4">
      <div class="actions">
        <%= form.submit class: "w-100 left btn btn-primary btn-lg submit-button" %>
      </div>
    </div>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
    <div class="card m-4">
      <div class="card-body">
        <%= post.title %>
        <%= post.publish_date %>
        <div class="card-footer bg-transparent border-success">
          <%= link_to 'Show', post, method: :get, class: 'btn btn-sm btn-primary text-white' %>
          <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-sm btn-warning text-white' %>
          <%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger text-white' %>
          <%= button_to 'Delete', post_path(post), method: :delete, class: "btn btn-danger btn-md" %>
        </div>
      </div>
    </div>

<% end %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag dom_id(@post) do %>
    <h5>Editing Post</h5>
    <hr>
    <%= render 'form', post: @post %>
    <hr>
    <%= link_to 'Show', @post %> |
    <%= link_to 'All Posts', posts_path %>
<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>




<h1>Tweeter</h1>

<%= turbo_stream_from "posts" %>

<%= turbo_frame_tag "post_form" do %>
    <%= render "posts/form", post: @post %>
<% end %>

<%= turbo_frame_tag "posts" do %>
    <%= render @posts %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @post.publish_date %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>